### Variables (環境設定)
@baseUrl = http://localhost:3000

### ユーザーを作成する
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "{{$datetime iso8601}}_{{$randomInt 1000 9999}}@example.com",
  "passwordHash": "securepassword123",
  "isAdmin": false
}


### ユーザーを参照する
GET http://localhost:3001/users
Content-Type: application/json


### develop/reset_db
POST http://localhost:3001/develop/reset_db
Content-Type: application/json

### develop/demo_user_login
POST http://localhost:3001/develop/demo_user_login
Content-Type: application/json

