### Variables (環境設定)
@baseUrl = http://localhost:3000

### ユーザーを作成する
POST http://localhost:3001
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "passwordHash": "securepassword123",
  "isAdmin": false
}


### ユーザーを参照する
GET http://localhost:3001
Content-Type: application/json
