@baseUrl = http://localhost:3001
@contentType = application/json

### Variables (環境設定)
@randomEmail = {{$datetime iso8601}}_{{$randomInt 1000 9999}}@example.com

### 開発者向けエンドポイント

###  データベースをリセット
POST {{baseUrl}}/develop/reset_db
Content-Type: {{contentType}}

###  デモユーザーでログイン
POST {{baseUrl}}/develop/demo_user_login
Content-Type: {{contentType}}

### 認証関連エンドポイント

###  ユーザー登録
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "name": "Alice",
  "email": "{{randomEmail}}",
  "password": "password"
}

###  ユーザーログイン
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "alice@example.com",
  "password": "password"
}

###  ユーザー登録
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "name": "Alice",
  "email": "{{randomEmail}}",
  "password": "password"
}


###  ユーザーログアウト
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}

###  me
GET {{baseUrl}}/auth/me
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkFsaWNlIiwiZW1haWwiOiJhbGljZUBleGFtcGxlLmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MjkxNzI0NjQsImV4cCI6MTcyOTI1ODg2NH0.7zOgO0yTczmvYxAwNqk5HOzweO293ogLD2YW9qAAdDg

###  管理者ログイン
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "password"
}

### ユーザー管理エンドポイント

###  ユーザーを作成
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "{{randomEmail}}",
  "password": "password"
}

###  ユーザー一覧を取得
GET {{baseUrl}}/users
Content-Type: {{contentType}}

###  ユーザー詳細を取得
GET {{baseUrl}}/users/2
Content-Type: {{contentType}}

###  ユーザー情報を変更
Put {{baseUrl}}/users/4
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "{{randomEmail}}",
  "isAdmin": false
}

###  ユーザー権限情報
PUT {{baseUrl}}/users/2/admin
Content-Type: {{contentType}}

{

}

###  ユーザー avatar情報を変更
PUT {{baseUrl}}/users/2/avatar
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="example.jpg"
Content-Type: image/jpeg

< ./backend/uploads/test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###  マイクロポスト一覧を取得
GET {{baseUrl}}/microposts
Content-Type: {{contentType}}

### テストエンドポイント

###  公開テスト
GET {{baseUrl}}/test/public
Content-Type: {{contentType}}

###  保護されたテスト
GET {{baseUrl}}/test/protected
Content-Type: {{contentType}}

###  プロフィールテスト（認証なし）
GET {{baseUrl}}/test/profile
Content-Type: {{contentType}}

###  プロフィールテスト（Bearerトークン付き）
GET {{baseUrl}}/test/profile
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjAyNC0xMC0xNVQxMjowNzoxNy4zMzBaXzI3MzkiLCJpZCI6MTIsImlhdCI6MTcyODk5Njg1MCwiZXhwIjoxNzI5MDAwNDUwfQ.w6v_HMo3HZPXDqjvc9Gt_wzgr_crEtsjGXinIKEDwW8

### 管理者テスト
GET {{baseUrl}}/test/admin
Content-Type: {{contentType}}