@baseUrl = http://localhost:3001
@contentType = application/json

### Variables (環境設定)
@randomEmail = {{$datetime iso8601}}_{{$randomInt 1000 9999}}@example.com

### ユーザーを作成する
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "{{randomEmail}}",
  "passwordHash": "securepassword123",
  "isAdmin": false
}

### ユーザーを作成する
POST {{baseUrl}}/users
Content-Type: {{contentType}}

{
  "name": "User {{randomEmail}}",
  "email": "{{randomEmail}}",
  "passwordHash": "securepassword123",
  "isAdmin": true
}

### ユーザーを参照する
GET {{baseUrl}}/users
Content-Type: {{contentType}}

### develop/reset_db
POST {{baseUrl}}/develop/reset_db
Content-Type: {{contentType}}

### develop/demo_user_login
POST {{baseUrl}}/develop/demo_user_login
Content-Type: {{contentType}}

### ユーザーログイン
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "alice@example.com",
  "passwordHash": "password"
}

### ユーザーregister
POST {{baseUrl}}/auth/register
Content-Type: {{contentType}}

{
  "email": "{{randomEmail}}",
  "passwordHash": "password"
}


### test/public
GET {{baseUrl}}/test/public
Content-Type: {{contentType}}

### test/protected
GET {{baseUrl}}/test/protected
Content-Type: {{contentType}}

### test/profile
GET {{baseUrl}}/test/profile
Content-Type: {{contentType}}

### test/profile with Bearer
GET {{baseUrl}}/test/profile
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiMjAyNC0xMC0xNVQxMjowNzoxNy4zMzBaXzI3MzkiLCJpZCI6MTIsImlhdCI6MTcyODk5Njg1MCwiZXhwIjoxNzI5MDAwNDUwfQ.w6v_HMo3HZPXDqjvc9Gt_wzgr_crEtsjGXinIKEDwW8

### ユーザーログイン
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "2024-10-15T12:07:17.330Z_2739@example.com",
  "passwordHash": "password"
}

### ユーザーログアウト
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}

### test/admin
GET {{baseUrl}}/test/admin
Content-Type: {{contentType}}

### アドミン ログイン
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "passwordHash": "password"
}

### ユーザーログアウト
POST {{baseUrl}}/auth/logout
Content-Type: {{contentType}}
